project:
  type: website
  output-dir: docs

website:
  title: "dashboard_practice"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - jupyter_practice.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



